from building import *
import os

cwd = GetCurrentDir()

inc = [
    cwd,
    cwd + '/include'
]

src = Glob('*.c')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = inc)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
